### PR TITLE
Shows poster if poster exists

### PR DESCRIPTION
**Pull request by Craytor**
Fixes issue #19.

### CODE REVIEW

**Review by kslimani — CHANGES_REQUESTED** [review]
Thank you @Craytor.
Could you please edit your PR and remove the dist files ?

**Comment by Craytor** [comment]
@kslimani, sure thing.

**Comment by Craytor** [comment]
@kslimani fixed.

**Comment by kslimani** [comment]
Thank you @Craytor 
LGTM - will make a new release version tomorrow at work.

**Comment by Craytor** [comment]
Thanks! Glad I could help out.

**Pull request merged**
